"""Prometheus metrics: HTTP instrumentation + domain counters/gauges."""
import time

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    CollectorRegistry,
    Counter,
    Gauge,
    Histogram,
    generate_latest,
)

registry = CollectorRegistry()

HTTP_REQUESTS = Counter(
    "http_requests_total", "Total HTTP requests",
    ["method", "path", "status"], registry=registry,
)
HTTP_LATENCY = Histogram(
    "http_request_duration_seconds", "Request latency",
    ["method", "path"],
    buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10),
    registry=registry,
)
SCANS_TOTAL = Counter(
    "engine_scans_total", "Engine scans executed", registry=registry,
)
SCAN_SIGNALS = Counter(
    "scan_signals_generated_total", "Signals generated by scans", registry=registry,
)
SCAN_ERRORS = Counter(
    "scan_errors_total", "Scans that reported engine errors", registry=registry,
)
LAST_SCAN_TS = Gauge(
    "last_scan_timestamp", "Unix time of the last scan attempt", registry=registry,
)
LAST_SCAN_SIGNALS = Gauge(
    "last_scan_signals", "Signals generated by the last completed scan", registry=registry,
)


def record_scan(signals: int, had_errors: bool) -> None:
    SCANS_TOTAL.inc()
    SCAN_SIGNALS.inc(signals)
    LAST_SCAN_TS.set_to_current_time()
    LAST_SCAN_SIGNALS.set(signals)
    if had_errors:
        SCAN_ERRORS.inc()


def render() -> tuple[bytes, str]:
    return generate_latest(registry), CONTENT_TYPE_LATEST


class MetricsMiddleware:
    """ASGI middleware: count + time every request except /metrics itself."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http" or scope.get("path") == "/metrics":
            await self.app(scope, receive, send)
            return

        method = scope.get("method", "?")
        path = scope.get("path", "?")
        status_holder = {"status": 500}
        start = time.perf_counter()

        async def send_wrapper(message):
            if message["type"] == "http.response.start":
                status_holder["status"] = message["status"]
            await send(message)

        try:
            await self.app(scope, receive, send_wrapper)
        finally:
            elapsed = time.perf_counter() - start
            HTTP_REQUESTS.labels(method, path, str(status_holder["status"])).inc()
            HTTP_LATENCY.labels(method, path).observe(elapsed)
